function net = ManeuversNet(X, Y,outputSize,maxEpochs)
[num_feature, temp] = size(X{1});
inputSize = num_feature;
outputMode = 'sequence';
numClasses = 5;
%,'InputWeightsL2Factor',0.01
layers = [ ...
    sequenceInputLayer(inputSize)
    %bilstmLayer()
    lstmLayer(outputSize,'OutputMode','last','InputWeightsL2Factor',0.1)
    %lstmLayer(outputSize/2,'OutputMode',outputMode,'InputWeightsL2Factor',0.2)
    %lstmLayer(outputSize/4,'OutputMode','last','InputWeightsL2Factor',0.3)
    dropoutLayer(0.3)
    fullyConnectedLayer(numClasses) 
    softmaxLayer
    classificationLayer];
miniBatchSize = 10;
options = trainingOptions('sgdm', ...
    'InitialLearnRate',0.01,...
    'LearnRateSchedule' ,'piecewise',...
    'LearnRateDropFactor',0.1,...
    'LearnRateDropPeriod',300,...
    'MaxEpochs',maxEpochs, ...
    'ValidationFrequency',100,...
    'MiniBatchSize',miniBatchSize,...
    'Shuffle', 'every-epoch',...
    'Plots','training-progress');
%    %'CheckpointPath','./model',...
%every-epoch
net = trainNetwork(X,Y,layers,options);

end